=== rdtproject/XMLPool/src/test/resources/Appointment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Appointment"
	xmlns:tns="http://www.example.org/Appointment" elementFormDefault="qualified">

	<element name="appointment" type="tns:Appointment" />

	<complexType name="Appointment">
		<sequence>
			<element name="date" type="date" />
			<element name="appartment" type="tns:Appartment" />
			<element name="teenant" type="tns:Teenant" />
		</sequence>
	</complexType>

	<complexType name="Appartment">
		<sequence>
			<element name="address" type="tns:Address" />
			<element name="floor" type="int" />
			<element name="freeFrom" type="date" />
			<element name="monthlyCosts" type="float" />
		</sequence>
	</complexType>

	<complexType name="Teenant">
		<sequence>
			<element name="gender" type="tns:Gender" />
			<element name="firstName" type="string" />
			<element name="lastName" type="string" />
			<element name="age" type="tns:Age" />
			<element name="salary" type="float" />
		</sequence>
	</complexType>

	<complexType name="Address">
		<sequence>
			<element name="streetName" type="string" />
			<element name="streetNr" type="int" />
			<element name="zipCode" type="string" />
		</sequence>
	</complexType>

	<simpleType name="Age">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M"></enumeration>
			<enumeration value="F"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== rdtproject/XMLPool/src/test/resources/Appointment.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:appointment xmlns:tns="http://www.example.org/Appointment"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Appointment Appointment.xsd ">
	<tns:date>2001-01-01</tns:date>
	<tns:appartment>
		<tns:address>
			<tns:streetName>Ugly street</tns:streetName>
			<tns:streetNr>2</tns:streetNr>
			<tns:zipCode>3013</tns:zipCode>
		</tns:address>
		<tns:floor>2</tns:floor>
		<tns:freeFrom>2001-01-01</tns:freeFrom>
		<tns:monthlyCosts>1430.22</tns:monthlyCosts>
	</tns:appartment>
	<tns:teenant>
		<tns:gender>M</tns:gender>
		<tns:firstName>Zdzislaw</tns:firstName>
		<tns:lastName>Kowalski</tns:lastName>
		<tns:age>34</tns:age>
		<tns:salary>6300.0</tns:salary>
	</tns:teenant>
</tns:appointment>
